import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

const inter = Inter({
   subsets: ["latin"],
   variable: "--font-inter",
});

export const metadata = {
   title: "My App",
   description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" className={inter.variable}>
         <body className={inter.className}>
            <Navbar />
            {children}
            <Footer />
         </body>
      </html>
   );
}
